name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout current
      uses: actions/checkout@v3
      with:
         repository: nvdaes/nvdaStoreMastodonBot
         path: main

    - name: Checkout store
      uses: actions/checkout@v3
      with:
         repository: nvdaes/addon-datastore
         path: store
         fetch-depth: 0
    - name: Read previous sha
      id: prevSha
      uses: juliangruber/read-file-action@v1
      with:
        path: ./main/sha.txt
    - name: Write diff
      run: |
        cd store
        git checkout views
        git diff --numstat ${{ steps.prevSha.outputs.content }}..HEAD views/en/latest > ../main/diff.txt

    - name: Get diff
      id: diff
      uses: juliangruber/read-file-action@v1
      with:
        path: ./main/diff.txt
    - name: Process diff
      id: processDiff
      uses: actions/github-script@v6
      with:
        script: |
          const diff = "${{ steps.diff.outputs.content }}"
          const files = diff.split('\n')
          const length = files.length
          if (length <== 1) {
            throw WNo files"
          }
          if (length === 2) {
            return ${{ steps.diff.outputs.content }}.split('/')[-1]
          }

    - name: Push changes
      run: |
        cd store
        git log -1 --pretty="format:%H" > ../main/sha.txt
        cd ../main

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
        git commit -m "Update sha"
        git push
