name: Check files changed and send toot

on:
  workflow_dispatch:
  
  workflow_call:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
    
jobs:

  diffs:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout current
      uses: actions/checkout@v5
      with:
         repository: nvdaes/nvdaStoreMastodonBot
         path: main

    - name: Read current sha
      id: currentSha
      uses: actions/github-script@v7
      with:
        script: |
          const cacheUrl = 'https://addonstore.nvaccess.org/cacheHash.json'
          const result = await github.request(cacheUrl)
          const data = result.data
          return data.trim()
        result-encoding: string
    - name: Restore cached hash
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ./old.json
        key: hash-${{ steps.currentSha.outputs.result }}

    - name: Download latest add-ons
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl --location --output new.json https://addonstore.nvaccess.org/en/all/new.json

    - name: Rename files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mv new.json old.json -f
    - name: Test
      run: |
        echo "{a": "b}" > a.json
        echo "{b": "c}" > b.json
        jsondiff a.json b.json

    - name: Send mail
      if: ${{ steps.buildMail.outputs.mailBody }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{ steps.buildMail.outputs.subject }}
        to: lista@nvdaes.groups.io
        from: Noelia Ruiz
        body: ${{steps.buildMail.outputs.mailBody }}

    - name: Send mail to feeds subgroup
      if: ${{ steps.buildToot.outputs.toot }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 'Add-ons #addonstore'
        to: feeds@nvda-addons.groups.io
        from: Noelia Ruiz
        body: ${{ steps.buildToot.outputs.toot }}

    - name: Send toot to Mastodon
      id: mastodon
      if: ${{ steps.buildToot.outputs.toot }}
      uses: cbrgm/mastodon-github-action@v1
      with:
        message: ${{ steps.buildToot.outputs.toot }}
        visibility: "public" # default: public
      env:
        MASTODON_URL: ${{ secrets.MASTODON_URL }} # https://example.social
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token

    - name: Always Save cache
      id: save
      if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache.outputs.cache-primary-key }}
        path: |
          ./old.json