name: Check files changed and send toot

on:
  workflow_dispatch:
  
  workflow_call:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
    
jobs:

  diffs:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout current
      uses: actions/checkout@v4

    - name: Read current sha
      id: currentSha
      uses: actions/github-script@v7
      with:
        script: |
          const getLastHash = require('./.github/workflows/getLastHash.js')
          const hash = await getLastHash({github})
          return hash
        result-encoding: string
    - name: Restore cached hash
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ./old.json
        key: hash-${{ steps.currentSha.outputs.result }}
        restore-keys: |
          hash-

    - name: Download latest add-ons
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl --location --output new.json https://addonstore.nvaccess.org/en/all/latest.json
        curl --location --output es.json https://addonstore.nvaccess.org/es/all/latest.json
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install lodash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install
    - name: Get diffs
      id: getDiff
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const getDiff = require('./.github/workflows/getDiff.js')
          const diff = getDiff({core})
          console.log(diff.length)

    - name: Rename files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mv new.json old.json -f
          
    - name: Send mail
      if: ${{ steps.getDiff.outputs.esMailBody }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{ steps.getDiff.outputs.esSubject }}
        #to: lista@nvdaes.groups.io
        to: nrm1977@gmail.com
        from: Noelia Ruiz
        body: "${{steps.getDiff.outputs.esMailBody }}\n\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Send mail to feeds subgroup
      if: ${{ steps.buildToot.outputs.toot }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 'Add-ons #addonstore'
        to: feeds@nvda-addons.groups.io
        from: Noelia Ruiz
        body: ${{ steps.buildToot.outputs.toot }}

    - name: Send toot to Mastodon
      id: mastodon
      if: ${{ steps.buildToot.outputs.toot }}
      uses: cbrgm/mastodon-github-action@v1
      with:
        message: ${{ steps.buildToot.outputs.toot }}
        visibility: "public" # default: public
      env:
        MASTODON_URL: ${{ secrets.MASTODON_URL }} # https://example.social
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token

    - name: Always Save cache
      id: save
      if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache.outputs.cache-primary-key }}
        path: |
          ./old.json