name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: windows-latest

    steps:

    - name: Checkout current
      uses: actions/checkout@v3
    - name: Get last commit of datastore
      uses: actions/github-script@v6
      with:
          script: |
            const url = 'https://api.github.com/repos/nvdaes/addon-datastore/commits'            const result = await github.request(diff_url)
                        const result = await github.request(url)
                        const commits = JSON.parse(result)
                        const lastCommit = commits[0]