name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout current
      uses: actions/checkout@v3
      with:
         repository: nvdaes/nvdaStoreMastodonBot
         path: main

    - name: Checkout store
      uses: actions/checkout@v3
      with:
         repository: nvaccess/addon-datastore
         path: store
         fetch-depth: 0
    - name: Read previous sha
      id: prevSha
      uses: juliangruber/read-file-action@v1
      with:
        path: ./main/sha.txt

    - name: Write diff
      run: |
        cd store
        git checkout views
        git diff --numstat ${{ steps.prevSha.outputs.content }}..HEAD views/en/latest > ../main/diff.txt
    - name: Read diff
      id: diff
      uses: juliangruber/read-file-action@v1
      with:
        path: ./main/diff.txt
    - name: Process diff
      id: processDiff
      if: '${{ steps.diff.outputs.content }} != "\n"'
      uses: actions/github-script@v6
      with:
        script: |
          const diff = `${{ steps.diff.outputs.content }}`
          console.log(`${diff}`)
          const filesChanged = diff.split("\n")
          core.setOutput('filesChanged', filesChanged)
          const numberOfFilesChanged = filesChanged.length -1
          core.setOutput('numberOfFilesChanged', numberOfFilesChanged)
          var filename = ''
          if (numberOfFilesChanged === 1) {
            var filename = diff.split(/\t/)[2]
          }
          core.setOutput('filename', filename)
          console.log(`${filename} ${numberOfFilesChanged}`)
        result-encoding: string
    - name: Get metadata
      id: getMetadata
      if: ${{ steps.processDiff.outputs.filename }}
      uses: ActionsTools/read-json-action@main
      with:
        file_path: "store/${{ steps.processDiff.outputs.filename }}"
    - name: Build toot
      id: buildToot
      if: '${{ steps.diff.outputs.numberOfFilesChanged }} >= "\n"'
      uses: actions/github-script@v6
      with:
        script: |
          var toot = ``
          const numberOfFilesChanged = ${{ steps.processDiff.outputs.numberOfFilesChanged}}
          if (numberOfFilesChanged === 1) {
            const name = `${{ steps.getMetadata.outputs.displayName }}`
            const version = `${{ steps.getMetadata.outputs.addonVersionName }}`
            const channel = `${{ steps.getMetadata.outputs.channel }}`
            const homepage = `${{ steps.getMetadata.outputs.homepage }}`
            const url = `${{ steps.getMetadata.outputs.URL }}`
            const sha = `${{ steps.getMetadata.outputs.sha256 }}`
            var toot = `${name} ${version}\nHomepage: ${homepage}\nDownload: ${url}\nSHA 256: ${sha}`
          } else {
            var toot = `Updated ${numberOfFilesChanged} add-ons`
          }
          console.log(toot)
          core.setOutput('toot', toot) 
        result-encoding: string
    - name: Write toot
      run: echo "${{ steps.buildToot.outputs.toot}}" > ./main/toot.txt

    - name: Push changes
      if: ${{ steps.processDiff.outputs.numberOfFilesChanged }} > 0
      run: |
        cd store
        git log -1 --pretty="format:%H" > ../main/sha.txt
        cd ../main

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
        git commit -m "Update sha"
        git push
