name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: windows-latest

    steps:

    - name: Checkout current
      uses: actions/checkout@v3
      with:
        path: main
        repository: nvdaes/nvdaStoreMastodonBot
        ref: main
    - name: Checkout addon-datastore repo
      uses: actions/checkout@v3
      with:
        path: datastore
        repository: nvdaes/addon-datastore
        ref: views
        fetch-depth: 0
    - name: Write hash
      run: |
        cd datastore
        git log -1 --pretty="format:%H" > ../main/hash.txt
    - name: Push changes
      run: |
        cd main
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -a -m "Update sha"
        git push origin HEAD:main