name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: windows-latest

    steps:

    - name: Checkout current
      uses: actions/checkout@v3
    - name: Get last commit of datastore
      id: getSha
      uses: actions/github-script@v6
      with:
          script: |
            const url = 'https://api.github.com/repos/nvdaes/addon-datastore/commits/HEAD'
                        const result = await github.request(url)
                        const commit = result.data
                        const sha = commit.sha
                        return sha
    - name: Write sha
      run: |
       echo "${{ steps.getSha.outputs.result }}" > sha.txt
    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -a -m "Update sha"
        git push