name: Check files changed

on:
  workflow_dispatch:
    
jobs:

  diffs:
  
    runs-on: windows-latest

    steps:

    - name: Checkout addon-datastore repo
      uses: actions/checkout@v3
      with:
        path: datastore
        repository: nvdaes/addon-datastore
        ref: views
        fetch-depth: 0
    - name: Write hash
      run: |
        cd datastore
        echo "HASH=git log -1 --pretty='format:%H'" >> $GITHUB_ENV
    - name: Show hash
      run: echo "${{ env.HASH }}"
